# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VK Client' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire', '~> 5.2'

pod 'SwiftyJSON', '~> 4.0'

pod 'RealmSwift', '~> 10.7.2'

# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
pod 'PromiseKit'

pod "Texture"


 # Pods for VK Client

end
